from django.conf.urls import include, url
from django.contrib import admin

from graphs import views

urlpatterns = [
    url(r'^http$', views.http_index, name='graphs/http-index'),
    url(r'^web-server/all/(?P<scan_date>\d+-\d+-\d+)$', views.http_server_all, name='graphs/server/all'),
    url(r'^web-server/(?P<port>[0-9]+)$', views.http_server, name='graphs/server'),
    url(r'^web-server/(?P<port>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.http_server, name='graphs/server'),
    url(r'^web-server/(?P<port>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)/(?P<product>[\w\s]+)$', views.http_server, name='graphs/server'),
    url(r'^operative-system/all/(?P<scan_date>\d+-\d+-\d+)$', views.operating_system_server_all, name='graphs/os/all'),
    url(r'^operative-system/(?P<port>[0-9]+)$', views.operating_system_server, name='graphs/os'),
    url(r'^operative-system/(?P<port>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.operating_system_server, name='graphs/os'),
    url(r'^device/all/(?P<scan_date>\d+-\d+-\d+)$', views.device_type_all, name='graphs/device/all'),
    url(r'^device/(?P<port>[0-9]+)$', views.device_type, name='graphs/device'),
    url(r'^device/(?P<port>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.device_type, name='graphs/device'),
    url(r'^https/key-bits/(?P<port>[0-9]+)$', views.key_bits, name='graphs/https/key-bits'),
    url(r'^https/key-bits/(?P<port>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.key_bits, name='graphs/https/key-bits'),
    url(r'^https/validation/(?P<port>[0-9]+)$', views.validation, name='graphs/https/validation'),
    url(r'^https/validation/(?P<port>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.validation, name='graphs/https/validation'),
    url(r'^https/signature/(?P<port>[0-9]+)$', views.signature, name='graphs/https/signature'),
    url(r'^https/signature/(?P<port>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.signature, name='graphs/https/signature'),
    url(r'^https/cipher-suite/(?P<port>[0-9]+)$', views.cipher_suite, name='graphs/https/cipher-suite'),
    url(r'^https/cipher-suite/(?P<port>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.cipher_suite, name='graphs/https/cipher-suite'),
    url(r'^https/tls_version/(?P<port>[0-9]+)$', views.tls_version, name='graphs/https/tls-version'),
    url(r'^https/tls_version/(?P<port>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.tls_version, name='graphs/https/tls-version'),
    url(r'^search$', views.search, name='search'),
    url(r'^search/(?P<port>[0-9]+)/(?P<ip>([0-9]{1,3}\.){3}[0-9]{1,3})/(?P<date>\d+-\d+-\d+)/(?P<direction>[\w]+)$', views.search_partial, name='search/partial'),
    url(r'^search/cert/(?P<ip>([0-9]{1,3}\.){3}[0-9]{1,3})/(?P<date>[\w\-]+)/(?P<direction>[\w]+)$', views.search_partial_cert, name='search/cert/partial'),
    url(r'^asn/top$', views.top_asn, name='asn/top-asn'),
    url(r'^web-server/all/as$', views.http_server_asn_search, name='graphs/asn/server'),
    url(r'^web-server/all/as/(?P<number>[0-9]+)$', views.http_server_all_asn, name='graphs/asn/server/all'),
    url(r'^web-server/all/as/(?P<number>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.http_server_all_asn, name='graphs/asn/server/all'),
    url(r'^web-server/as/(?P<number>[0-9]+)/(?P<port>[0-9]+)$', views.http_server_asn, name='graphs/asn/server'),
    url(r'^web-server/as/(?P<number>[0-9]+)/(?P<port>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.http_server_asn, name='graphs/asn/server'),
    url(r'^web-server/all/as$', views.http_server_asn_search, name='graphs/asn/server'),
    url(r'^operative-system/(?P<port>[0-9]+)/as$', views.operating_system_server_asn_search, name='graphs/asn/os'),
    url(r'^operative-system/all/as/(?P<number>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.operating_system_server_asn_all, name='graphs/asn/os/all'),
    url(r'^operative-system/(?P<port>[0-9]+)/as/(?P<number>[0-9]+)$', views.operating_system_server_asn, name='graphs/asn/os'),
    url(r'^operative-system/(?P<port>[0-9]+)/as/(?P<number>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.operating_system_server_asn, name='graphs/asn/os'),
    url(r'^device/(?P<port>[0-9]+)/as$', views.device_type_asn_search, name='graphs/asn/device'),
    url(r'^device/all/as/(?P<number>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.device_type_asn_all, name='graphs/asn/device/all'),
    url(r'^device/(?P<port>[0-9]+)/as/(?P<number>[0-9]+)$', views.device_type_asn, name='graphs/asn/device'),
    url(r'^device/(?P<port>[0-9]+)/as/(?P<number>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.device_type_asn, name='graphs/asn/device'),
    url(r'^https/key-bits/(?P<port>[0-9]+)/as$', views.key_bits_asn_search, name='graphs/https/asn/key-bits'),
    url(r'^https/key-bits/(?P<port>[0-9]+)/as/(?P<number>[0-9]+)$', views.key_bits_asn, name='graphs/https/asn/key-bits'),
    url(r'^https/key-bits/(?P<port>[0-9]+)/as/(?P<number>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.key_bits_asn, name='graphs/https/asn/key-bits'),
    url(r'^https/validation/(?P<port>[0-9]+)/as$', views.validation_asn_search, name='graphs/https/asn/validation'),
    url(r'^https/validation/(?P<port>[0-9]+)/as/(?P<number>[0-9]+)$', views.validation_asn, name='graphs/https/asn/validation'),
    url(r'^https/validation/(?P<port>[0-9]+)/as/(?P<number>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.validation_asn, name='graphs/https/asn/validation'),
    url(r'^https/signature/(?P<port>[0-9]+)/as$', views.signature_asn_search, name='graphs/https/asn/signature'),
    url(r'^https/signature/(?P<port>[0-9]+)/as/(?P<number>[0-9]+)$', views.signature_asn, name='graphs/https/asn/signature'),
    url(r'^https/signature/(?P<port>[0-9]+)/as/(?P<number>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.signature_asn, name='graphs/https/asn/signature'),
    url(r'^https/cipher-suite/(?P<port>[0-9]+)/as$', views.cipher_suite_asn_search, name='graphs/https/asn/cipher-suite'),
    url(r'^https/cipher-suite/(?P<port>[0-9]+)/as/(?P<number>[0-9]+)$', views.cipher_suite_asn, name='graphs/https/asn/cipher-suite'),
    url(r'^https/cipher-suite/(?P<port>[0-9]+)/as/(?P<number>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.cipher_suite_asn, name='graphs/https/asn/cipher-suite'),
    url(r'^https/tls_version/(?P<port>[0-9]+)/as$', views.tls_version_asn_search, name='graphs/https/asn/tls-version'),
    url(r'^https/tls_version/(?P<port>[0-9]+)/as/(?P<number>[0-9]+)$', views.tls_version_asn, name='graphs/https/asn/tls-version'),
    url(r'^https/tls_version/(?P<port>[0-9]+)/as/(?P<number>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)$', views.tls_version_asn, name='graphs/https/asn/tls-version'),
    url(r'^search$', views.search, name='search'),
    # product version hasn't been implemented yet (i think?)
    # url(r'^web-server/(?P<port>[0-9]+)/(?P<scan_date>\d+-\d+-\d+)/(?P<product>[\w\s]+)$', views.http_server, name='graphs/asn/server'),
    # url(r'^asn$', views.asn, name='graphs/asn'),
]

